import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - this file is generated by the build
import * as build from "../build/server/index.js";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => context.env,
});
